
name: Deploying Springboot(War) to Tomcat on Azure Windows Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-springboot-app:
    name: Build Springboot Application
    runs-on: ubuntu-latest
    steps:
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Java Version
        run: java -version

      - name: Download the code
        uses: actions/checkout@v3

      - name: Fix the Permissions of mvnw command
        run: chmod +x mvnw

      - name: Build the code
        run: ./mvnw package

      - name: Verify the Build is Created or not
        run: ls -l target/*.war
      
      - name: Deploy the Build to Tomcat (SSH to window)
        uses: appleboy/scp-action@master
        with:
          local: './target/apiservice-0.0.1-SNAPSHOT.war'                                                 
          remote: 'C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps'                                               
          host: ${{secrets.HOST}}                                                                       
          user: ${{secrets.USER}}                                     
          password: ${{secrets.PASSWORD}}                                                                   
          pre_upload: echo "This will be executed before the upload!"  
          post_upload: echo "This will be executed after the upload!"  
          ssh_options: -o StrictHostKeyChecking=no                     
          scp_options: -v                                            
